version: "3.8"

services:
    postgres:
        image: postgres:12.18
        container_name: backend-database
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        ports:
            - "6942:5432"
